### ISSUE TITLE
The pre-trained model weight

### ISSUE THREAD

**Issue by bboylyg** [VinAIResearch/input-aware-backdoor-attack-release#1]
Hi, I have downloaded the pre-trained model weight for CIFAR-10, but there is only one weight named “all2one_cifar10_ckpt.pth.tar” after I extract the zip file. So where the corresponding weight of the generated model for "G_m" and "G_t"?

**Comment by anhttran** [comment]
Thanks for your interest on our work.

All network weights are included in that file. You can check the evaluation code:

**Comment by bboylyg** [comment]
Thanks for your replay, I will close this question~
